# Generated by Django 3.1.6 on 2021-03-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='created_by',
            new_name='author',
        ),
    ]
