# Generated by Django 3.1.6 on 2021-03-09 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210309_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watched_by',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
